# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Haiti's Lost Children
email: paulkfranz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Haiti's Lost Children was a multimedia project funded by the Pulitzer Center on Crisis Reporting in 2010. The project is no longer updated, but the original video stories, photographs, and project foreward have been preserved and published here. Although research and production on this project ended in late 2010, Haiti still struggles with providing basic infrastructure and education services to its citizens.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "" # the base hostname & protocol for your site
twitter_username: pkfranz
github_username:  pkfranz
disqus_username:

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: 'assets/images'
